import Mathlib.Algebra.Group.MinimalAxioms
import Mathlib.GroupTheory.OrderOfElement

/--
DF_1_1_15:
  Prove that $(a_1 a_2 \ldots a_n)^{-1} = a_n^{-1} a_{n - 1}^{-1} \ldots a_1^{-1}$
  for all $a_1, a_2, \ldots, a_n \in G$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_15 {G : Type*} [Group G] (l : List G) :
    (l.foldl (· * ·) 1)⁻¹ = (l.map (·⁻¹)).foldr (· * ·) 1 :=
  sorry

/--
DF_1_1_16:
  Let $x$ be an element of $G$.
  Prove that $x^2 = 1$ if and only if $|$ is either 1 or 2.

Contributor: Jihoon Hyun
-/

theorem DF_1_1_16 {G : Type*} [Group G] {x : G} :
    x ^ 2 = 1 ↔ (orderOf x = 1 ∨ orderOf x = 2) :=
  sorry

/--
DF_1_1_17:
  Let $x$ be an element of $G$.
  Prove that if $|x| = n$ for some positive integer $n$ then $x^{-1} = x^{n - 1}$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_17 {G : Type*} [Group G] {x : G} (h : 0 < orderOf x) :
    x⁻¹ = x ^ (orderOf x - 1) :=
  sorry

/--
DF_1_1_18:
  Let $x$ and $y$ be elements of $G$.
  Prove that $xy = yx$ if and only if $y^{-1}xy = x$ if and only if $x^{-1}y^{-1}xy = 1$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_18 {G : Type*} [Group G] (x y : G) :
    List.TFAE [
      x * y = y * x,
      y⁻¹ * x * y = x,
      x⁻¹ * y⁻¹ * x * y = 1
    ] :=
  sorry

/--
DF_1_1_19:
  Let $x \in G$ and let $a, b \in \mathbb{Z}^+$.
  (a) Prove that $x^{a + b} = x^a x^b$ and $(x^a)^b = x^{ab}$.
  (b) Prove that $(x^a)^{-1} = x^{-a}$.
  (c) Establish part (a) for arbitrary integers $a$ and $b$ (positive, negative or zero).

Contributor: Jihoon Hyun
-/
theorem DF_1_1_19_a {G : Type*} [Group G] {x : G} {a b : ℕ} (ha : 0 < a) (hb : 0 < b) :
    x ^ (a + b) = x ^ a * x ^ b ∧ (x ^ a) ^ b = x ^ (a * b) :=
  sorry

theorem DF_1_1_19_b {G : Type*} [Group G] {x : G} {a : ℤ} :
    (x ^ a)⁻¹ = x ^ (-a) :=
  sorry

theorem DF_1_1_19_c {G : Type*} [Group G] {x : G} {a b : ℤ} :
    x ^ (a + b) = x ^ a * x ^ b ∧ (x ^ a) ^ b = x ^ (a * b) :=
  sorry

/--
DF_1_1_20:
  For $x$ an element in $G$ show that $x$ and $x^{-1}$ have the same order.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_20 {G : Type*} [Group G] {x : G} :
    orderOf x = orderOf x⁻¹ :=
  sorry

/--
DF_1_1_21:
  Let $G$ be a finite group and let $x$ be an element of $G$ of order $n$.
  Prove that if $G$ is odd, then $x = (x^2)^k$ for some integer $k ≥ 1$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_21 {G : Type*} [Group G] [Fintype G] (h : Odd (Fintype.card G)) {x : G} :
    ∃ (k : ℕ), 1 ≤ k ∧ x = (x ^ 2) ^ k :=
  sorry

/--
DF_1_1_22:
  If $x$ and $g$ are elements of the group $G$, prove that $|x| = |g^{-1}xg|$.
  Deduce that $|ab| = |ba|$ for all $a, b \in G$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_22_1 {G : Type*} [Group G] {x g : G} :
    orderOf x = orderOf (g⁻¹ * x * g) :=
  sorry

theorem DF_1_1_22_2 {G : Type*} [Group G] {a b : G} :
    orderOf (a * b) = orderOf (b * a) :=
  sorry

/--
DF_1_1_23:
  Suppose $x \in G$ and $|x| = n < \infty$.
  If $n = st$ for some positive integers $s$ and $t$,
  prove that $|x^s| = t$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_23
    {G : Type*} [Group G] {x : G} (hx : orderOf x ≠ 0)
    {s : ℕ} (hs : 0 < s) {t : ℕ} (ht : 0 < t) (h : orderOf x = s * t) :
    orderOf (x ^ s) = t :=
  sorry

/--
DF_1_1_24:
  If $a$ and $b$ are \textit{commuting elements} of $G$,
  prove that $(ab)^n = a^n b^n$ for all $n \in \mathbb{Z}$.
  [Do this by induction for positive $n$ first.]
  
Contributor: Jihoon Hyun
-/
theorem DF_1_1_24 {G : Type*} [CommGroup G] (a b : G) (n : ℤ) :
    (a * b) ^ n = a ^ n * b ^ n :=
  sorry

/--
DF_1_1_25:
  Prove that if $x^2 = 1$ for all $x \in G$ then $G$ is abelian.

Contributor: Jihoon Hyun
-/
def DF_1_1_25 {G : Type*} [Group G] (h : ∀ x : G, x ^ 2 = 1) :
    CommGroup G where
  mul_comm := sorry

/--
DF_1_1_26:
  Assume $H$ is a nonempty subset of $(G, \bigstar)$ which is closed under the binary operation on
  $G$ and is closed under inverses, i.e., for all $h$ and $k \in H$, $hk$ and $h^{-1} \in H$.
  Prove that $H$ is a group under the operation $\bigstar$ restricted to $H$
  (such a subset $H$ is called a \textit{subgroup} of $G$).

Contributor: Jihoon Hyun
-/
def DF_1_1_26
    {G : Type*} [Group G]
    (H : Set G) (hmul : ∀ a ∈ H, ∀ b ∈ H, a * b ∈ H) (hinv : ∀ a ∈ H, a⁻¹ ∈ H) :
    Group H :=
  sorry

/--
DF_1_1_27:
  Prove that if $x$ is an element of the group $G$ then $\{x^n | n \in \mathbb{Z}\}$ is a subgroup
  (cf. the preceding exercise) of $G$ (called the \textit{cyclic subgroup} of $G$ generated by $x$).

Contributor: Jihoon Hyun
-/
def DF_1_1_27 {G : Type*} [Group G] (g : G) :
    Group {x : G | ∃ n, x = g ^ n} :=
  sorry

/--
DF_1_1_28:
  Let $(A, \bigstar)$ and $(B, \diamond)$ be groups and let $A \times B$ be their direct product
  (as defined in Example 6).
  Verify all the group axioms for $A \times B$:
  (a) prove that the associative law holds:
      for all $(a_i, b_i) \in A \times B$, $i = 1, 2, 3$
      $(a_1, b_1) [(a_2, b_2) (a_3, b_3)] = [(a_1, b_1) (a_2, b_2)] (a_3, b_3)$,
  (b) prove that $(1, 1)$ is the identity of $A \times B$, and
  (c) prove that the inverse of $(a, b)$ is $(a^{-1}, b^{-1}$.

Contributor: Jihoon Hyun
-/
def DF_1_1_28_a {A B : Type*} [Group A] [Group B] :
    Group (A × B) :=
  haveI instMul : Mul (A × B) := ⟨fun g₁ g₂ ↦ (g₁.fst * g₂.fst, g₁.snd * g₂.snd)⟩
  haveI instInv : Inv (A × B) := ⟨fun g ↦ (g.fst⁻¹, g.snd⁻¹)⟩
  haveI instOne : One (A × B) := ⟨(1, 1)⟩
  @Group.ofLeftAxioms (A × B) instMul instInv instOne
    (sorry /- (a) -/)
    (sorry /- (b) -/)
    (sorry /- (c) -/)

/--
DF_1_1_29:
  Prove that $A \times B$ is an abelian group if and only if both $A$ and $B$ are abelian.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_29 {A B : Type*} [Group A] [Group B] :
    Std.Commutative (· * · : A × B → A × B → A × B) ↔
    (Std.Commutative (· * · : A → A → A) ∧ Std.Commutative (· * · : B → B → B)) := by
  sorry

/--
DF_1_1_30:
  Prove that the elements $(a, 1)$ and $(1, b)$ of $A \times B$ commute and deduce that the order
  of $(a, b)$ is the least common multiple of $|a|$ and $|b|$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_30 {A B : Type*} [Group A] [Group B] (a : A) (b : B) :
    (a, 1) * (1, b) = (1, b) * (a, 1) ∧ orderOf (a, b) = (orderOf a).lcm (orderOf b) :=
  sorry

/--
DF_1_1_31:
  Prove that any finite group $G$ of even order contains an element of order 2.
  [Let $t(G)$ be the set $\{g \in G | g ≠ g^{-1}\}$.
  Show that $t(G)$ has an even number of elements and every nonidentity element of $G - t(G)$ has
  order 2.]

Contributor: Jihoon Hyun
-/
theorem DF_1_1_31 {G : Type*} [Group G] [Fintype G] (h : Even (Fintype.card G)) :
    ∃ x : G, orderOf x = 2 :=
  sorry

/--
DF_1_1_32:
  If $x$ is an element of finite order $n$ in $G$, prove that the elements
  $1, x, x^2, \ldots, x^{n - 1}$ are all distinct.
  Deduce that $|x| \leq |G|$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_32 {G : Type*} [Group G] [Fintype G] (x : G) :
    ((List.range (orderOf x)).map (x ^ ·)).Nodup ∧ orderOf x ≤ Fintype.card G :=
  sorry

/--
DF_1_1_33:
  Let $x$ be an element of finite order $n$ in $G$.
  (a) Prove that if $n$ is odd then $x^i \neq x^{-i}$ for all $i = 1, 2, \ldots, n - 1$.
  (b) Prove that if $n = 2k$ and $1 \leq i < n$ then $x^i = x^{-i}$ if and only if $i = k$.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_33_a
    {G : Type*} [Group G] [Fintype G] (h : Odd (Fintype.card G)) (x : G)
    (i : ℤ) (hi₁ : 0 < i) (hi₂ : i < Fintype.card G) :
    x ^ i ≠ x ^ (-i) :=
  sorry

theorem DF_1_1_33_b
    {G : Type*} [Group G] [Fintype G] (h : Even (Fintype.card G)) (x : G)
    {i : ℤ} (hi₁ : 0 < i) (hi₂ : i < Fintype.card G) :
    x ^ i = x ^ (-i) ↔ i = (Fintype.card G) / 2 :=
  sorry

/--
DF_1_1_34:
  If $x$ is an element of infinite order in $G$, prove that the elements $x^n, n \in \mathbb{Z}$
  are all distinct.

Contributor: Jihoon Hyun
-/
theorem DF_1_1_34 {G : Type*} [Group G] {x : G} (h : orderOf x = 0) :
    Function.Injective fun n : ℤ ↦ x ^ n :=
  sorry

/--
DF_1_1_35:
  If $x$ is an element of finite order $n$ in $G$, use the Division Algorithm to show that
  \textit{any} integral power of $x$ equals one of the elements in the set
  $\{1, x, x^2, \ldots, x^{n - 1}\}$
  (so these are all the distinct elements of the cyclic subgroup (cf. Exercise 27 above) of $G$
  generated by $x$).

Contributor: Jihoon Hyun
-/
theorem DF_1_1_35 {G : Type*} [Group G] [Fintype G] (x : G) (n : ℤ) :
    x ∈ (List.range (Fintype.card G)).map (x ^ ·) :=
  sorry
